#! /bin/sh

# Print a variable's value from the specified Makefile
#
# Usage:
# $ makefile-getvar path/to/makefile VARIABLE_NAME

make --file - $2.getvar <<EOF
include $1

%.getvar:
	@echo \$(\$*)
EOF
